version: '3.8'

services:
  db:
    image: postgres:15
    container_name: vendor_postgres
    environment:
      POSTGRES_USER: vendor_user
      POSTGRES_PASSWORD: vendor_pass
      POSTGRES_DB: vendor_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
