server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/vendor_db
    username: vendor_user
    password: vendor_pass
  jpa:
    hibernate:
      ddl-auto: validate # Ensures Flyway controls migrations
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    placeholders.db_compatibility_version: 14
    ignore-failed-future-migration: true
  application:
    name: VendorManagementApp

logging:
  level:
    org.springframework: INFO

springdoc:
  swagger-ui:
    path: /swagger-ui.html

