server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/vendor_db
    username: vendor_user
    password: vendor_pass
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: VendorManagementApp

logging:
  level:
    org.springframework: INFO
